### ISSUE TITLE
orTime and submit combination

### ISSUE THREAD

**Issue by DavDavid** [vsilaev/tascalate-concurrent#12]
When I execute this code:

```
CompletableTask
  .submit(this::doTask, executor)
  .orTimeout(Duration.ofSeconds(5L))
  .whenComplete((res, err) -> {
    if (res != null)
	System.out.println(res);
    else
        System.out.println(err.getMessage());
});

private String doTask () throws Exception {
  TimeUnit.SECONDS.sleep(3);
  if (true)
    throw new Exception("my error");
  return "executed ok";
}
```
I never get "my error" exception after 3 secs, only TimeoutException after 5 secs with "Timeout after PT5S" message.
If I remove orTimeout(...) line, I get "my error" exception.
Is there any way to catch both exceptions?

Thanks

**Comment by vsilaev** [comment]
Confirmed. The issue affects both orTimeout and onTimeout -- working on this

**Comment by vsilaev** [comment]
Dav,

Could you please verify with the sources from master that the issues is fixed?
Please notice that the artifact has new coordinates:
```xml
	<groupId>net.tascalate</groupId>
	<artifactId>net.tascalate.concurrent</artifactId>
	<version>1.0.0-SNAPSHOT</version>
```

**Comment by DavDavid** [comment]
Sorry, but how can I verify it with maven? Do I need a special repository? Maven says that this artifact doesn't exist.

**Comment by vsilaev** [comment]
It's necessary to clone a repo locally. Nevermind, I will release new build shortly.

**Comment by vsilaev** [comment]
Build is released with the fix mentioned
