### ISSUE TITLE
Typo in DelayPolicy#withMinDelay

### ISSUE THREAD

**Issue by borisfox-redcom** [vsilaev/tascalate-concurrent#15]
There's a called method name typo in the winMinDelay(mindelay, timeUnit) method of the DelayPolicy interface:
```
    default DelayPolicy<T> withMinDelay(long minDelay, TimeUnit timeUnit) {
        return withMaxDelay(Timeouts.toDuration(minDelay, timeUnit));
    }
```
Apparently it should call withMinDelay(duration).

**Comment by vsilaev** [comment]
Confirmed, fix is just committed, will release a new version within 1-2 days
