### ISSUE TITLE
Feature enhancement on cancel

### ISSUE THREAD

**Issue by deanorderly** [vsilaev/tascalate-concurrent#16]
I like twitter Futures model where I can cancel the future I receive AND it cancels ALL futures in the chain UNLESS someone broke the chain by nulling out the cancel handler.  This is really nice as it cancels the future you are waiting on AND any other futures that may be outstanding so those lambas will not run since I cancelled the entire request.  This would reclaim all the processing on the cancel unlike java futures which only cancel the first future.

SO post was closed but is here
https://stackoverflow.com/questions/62106428/is-there-a-better-way-for-cancelling-a-chain-of-futures-in-java?noredirect=1#comment109864875_62106428

closed because the above I guess is an opinion.

Dean

**Comment by vsilaev** [comment]
Dean,

I don't understand what part of functionality is missing. Have you read "6. DependentPromise" section of documentation? Also, there is a `Promise.onCancel` method that allows to run cancellation action outside futures chain.

**Comment by deanorderly** [comment]
ah, yes, I totally missed that........it's an awesome doc..it's just very very long.  I think I needed a table of contents.

anyways, thanks!!!!
