### ISSUE TITLE
MultitargetException swallows Exceptions

### ISSUE THREAD

**Issue by buko** [vsilaev/tascalate-concurrent#18]
MultitargetException swallows underlying Exceptions making it absolutely impossible to determine what the original, underlying exception was. [The MultitargetException constructor takes a list of Exceptions](https://github.com/vsilaev/tascalate-concurrent/blob/472f078cfdc2a60589f1041c13b8c11ba1037dc9/src/main/java/net/tascalate/concurrent/MultitargetException.java#L35) and makes no attempt to initCause() and set any of the exceptions in the list as a cause of the MultitargetException. When a MultitargetException occurs it is **impossible** to what caused the MultitargetException.

The MultitargetException constructor should change. Specifically:
1) If the list is an empty an IllegalArgumentException should be thrown.
2) The constructor should take the first element of the list and invoke initCause() with the first element as a parameter.

This should make it possible to always be able to determine what caused a MultitargetException.

Additionally the MultitargetException should override Throwable.getMessage(). When an exception occurs we really need as much information as possible as to why the exception occurred. Ideally MultitargetException.getMessage() would print out the number of exceptions and then print out detailed information about each exception occurred. Minimally we need to see the getMessage() for each of the Exceptions in the list. 

MultitargetException maintains its own list of throwables. Instead [MultitargetException should use the standard SuppressedException mechanism](https://www.baeldung.com/java-suppressed-exceptions). If there is more than one exception in the list than all remaining exceptions (except the first which is passed to initCause()) should be passed to addSupressed.

The current version of MultitargetException which doesn't use initCause and doesn't use addSupressed is a big problem. Exceptions occur in our background threadpools and in the curent design it is impossible to determine what those exceptions were without writing custom code to "unwrap" the exception. This makes the library very difficult to use.

**Comment by vsilaev** [comment]
Hello, buko

Let us elaborate on this issue a bit more.

First, what is your scenario for logging exceptions? What is the logger you are using? And what version of Tascalate Concurrent are you using?

Second, yes, neither cause nor suppressed exceptions are initialized. All in all, what is a cause when there are multiple ones? And using `addSuppresed` sounds to me as an API abuse. Probably I will add it but only if there are no other mechanism to fix the issue.

Third, I did some coding for dumping error info. To verify the functionality please try running [TestMultitargetExceptionTraces](https://github.com/vsilaev/tascalate-concurrent/blob/master/src/test/java/net/tascalate/concurrent/TestMultitargetExceptionTraces.java) (just copy sources -- it depends only on the Tascalate Concurrent lib).

Also, you can replace a line with
```java
e.printStackTrace(); // line 11
```
with the following:
```java
System.getLogger("any").log(Level.ERROR, "MY ERROR", e);
```
to verify that dumping errors works.
For me the output is:
```
net.tascalate.concurrent.MultitargetException
	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:21)
	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err(TestMultitargetExceptionTraces.java:17)
	at net.tascalate.concurrent.TestMultitargetExceptionTraces.main(TestMultitargetExceptionTraces.java:10)
	[2] -> java.lang.NoSuchMethodError: Data not found
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_2(TestMultitargetExceptionTraces.java:47)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_1(TestMultitargetExceptionTraces.java:43)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b(TestMultitargetExceptionTraces.java:39)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:24)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err(TestMultitargetExceptionTraces.java:17)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.main(TestMultitargetExceptionTraces.java:10)
	[4] -> java.lang.IllegalArgumentException: Something wrong
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.a(TestMultitargetExceptionTraces.java:33)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:25)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err(TestMultitargetExceptionTraces.java:17)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.main(TestMultitargetExceptionTraces.java:10)
	    ... Caused by: java.lang.NoSuchMethodError: Data not found
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_2(TestMultitargetExceptionTraces.java:47)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_1(TestMultitargetExceptionTraces.java:43)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b(TestMultitargetExceptionTraces.java:39)
	    ... 	... 4 more
	[6] -> net.tascalate.concurrent.MultitargetException
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:26)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err(TestMultitargetExceptionTraces.java:17)
	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.main(TestMultitargetExceptionTraces.java:10)
	    ... 	[0] -> java.lang.IllegalStateException: State is forbidden
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.c_2(TestMultitargetExceptionTraces.java:61)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.c_1(TestMultitargetExceptionTraces.java:57)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.c(TestMultitargetExceptionTraces.java:53)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:26)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err(TestMultitargetExceptionTraces.java:17)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.main(TestMultitargetExceptionTraces.java:10)
	    ... 	[1] -> java.lang.NoSuchMethodError: Data not found
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_2(TestMultitargetExceptionTraces.java:47)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_1(TestMultitargetExceptionTraces.java:43)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.b(TestMultitargetExceptionTraces.java:39)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:26)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err(TestMultitargetExceptionTraces.java:17)
	    ... 	    ... 	at net.tascalate.concurrent.TestMultitargetExceptionTraces.main(TestMultitargetExceptionTraces.java:10)
```

If your logging framework doesn't support dumping stack trace, then it's pretty easy to dump MultitargetException to StringWritter:
```java
// e is a MultitargetException here
java.io.StringWriter w = new java.io.StringWriter();
e.printStackTrace(new java.io.PrintWriter(w));
System.out.println(w.toString());
```
Waiting for your reply.

**Comment by buko** [comment]
We're using the latest version from maven.

It really is important to initialize the cause and the suppressed exceptions for MultitargetException. We have automated monitoring systems that are inspecting  cause and suppressed exceptions and looking for specific types. It seems very strange that these systems break because MultitargetException, even though it clearly has a cause, doesn't expose that to the world. It seems to me a good idea to always pick the first exception as the cause and add the rest as suppressed.

Overriding printStackTrace() is a good idea but I would be concerned that it's not possible to retrieve the actual underlying Exception objects from MultitargetException without writing special code specifically for MultitargetException. We actually have code that knows how to work with the standard APIs and generate detailed error reports.

**Comment by vsilaev** [comment]
Hello,

Now I see your point. When I dump `new IOException("Invalid user input",  new MultitargetException(excepionsList))` I see truncated output, while by default `Throwable.printStackTrace` inspects causes and suppressedExceptions.

I did a rough test and add all exceptions as suppressed, here is an output:
```
SEVERE: MY ERROR
java.io.IOException: Invalid user input
	at net.tascalate.concurrent.TestMultitargetExceptionTraces.outer(TestMultitargetExceptionTraces.java:18)
	at net.tascalate.concurrent.TestMultitargetExceptionTraces.main(TestMultitargetExceptionTraces.java:11)
Caused by: net.tascalate.concurrent.MultitargetException
	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:26)
	at net.tascalate.concurrent.TestMultitargetExceptionTraces.err(TestMultitargetExceptionTraces.java:22)
	... 1 more
	Suppressed: java.lang.NoSuchMethodError: Data not found
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_2(TestMultitargetExceptionTraces.java:52)
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_1(TestMultitargetExceptionTraces.java:48)
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.b(TestMultitargetExceptionTraces.java:44)
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:29)
		... 2 more
	Suppressed: java.lang.IllegalArgumentException: Something wrong
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.a(TestMultitargetExceptionTraces.java:38)
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:30)
		... 2 more
	Caused by: java.lang.NoSuchMethodError: Data not found
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_2(TestMultitargetExceptionTraces.java:52)
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_1(TestMultitargetExceptionTraces.java:48)
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.b(TestMultitargetExceptionTraces.java:44)
		... 4 more
	Suppressed: net.tascalate.concurrent.MultitargetException
		at net.tascalate.concurrent.TestMultitargetExceptionTraces.err_1(TestMultitargetExceptionTraces.java:31)
		... 2 more
		Suppressed: java.lang.IllegalStateException: State is forbidden
			at net.tascalate.concurrent.TestMultitargetExceptionTraces.c_2(TestMultitargetExceptionTraces.java:66)
			at net.tascalate.concurrent.TestMultitargetExceptionTraces.c_1(TestMultitargetExceptionTraces.java:62)
			at net.tascalate.concurrent.TestMultitargetExceptionTraces.c(TestMultitargetExceptionTraces.java:58)
			... 3 more
		Suppressed: java.lang.NoSuchMethodError: Data not found
			at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_2(TestMultitargetExceptionTraces.java:52)
			at net.tascalate.concurrent.TestMultitargetExceptionTraces.b_1(TestMultitargetExceptionTraces.java:48)
			at net.tascalate.concurrent.TestMultitargetExceptionTraces.b(TestMultitargetExceptionTraces.java:44)
			... 3 more
```

Is it enough? I see no reason to add arbitrary cause. Or I can: (A) add a cause when there is a single exception and do not add suppressed at all in this case OR (B) add all exceptions as suppressed when there are multiple.

Is it ok for you?

**Comment by buko** [comment]
Adding all the exceptions as suppressed works fine. That kind of output is exactly what we're looking for and what we hope to find when we examine the cause/supressed exceptions.

I also think it would be a good idea for MultitargetException to override Throwable.getMessage(). Right now MultitargetException doesn't override this method and provide any summary of what happened. It would be good if  MultitargetException could print a message summarizing what happened, even if the exception stack trace wasn't available. This could look like:

```java
 public String getMessage() {
        List<Throwable> listCopy = getErrors();
        StringBuilder sb = new StringBuilder("A MultitargetException has " + listCopy.size() + " exceptions.  They are:\n");
        
        int lcv = 1;
        for (Throwable th : listCopy) {
            sb.append(lcv++ + ". " + th.getClass().getName() + ((th.getMessage() != null) ? ": " + th.getMessage() : "" ) + "\n");
        }
        
        return sb.toString();
    }
```

**Comment by vsilaev** [comment]
I will not overwrite `getMessage` -- it's used for dumping exceptions in `Trowable.printStackTrace` hence the output would contain a lot of duplicated (and, hence, confusing data). Instead, I'll try to override `toString()` -- should be enough. All the rest will be available via standard `Trowable.printStackTrace` functionality that dumps full info of regular `cause` and `suppressed`.

**Comment by vsilaev** [comment]
https://github.com/vsilaev/tascalate-concurrent/commit/8debc4afff23c71b39bb01c589ad19095a107749

Indeed, I have to overwrite `getMessage` to include brief info about "nested" exceptions and `toString` to avoid using `getMessage` (infinite recurion otherwise).

Please get sources and check locally, the next build will be released within 2-5 days.

**Comment by vsilaev** [comment]
I take back my words about API abuse with `addSuppressed`.
`java.net.URLClassLoader`, method `close` -- there is some kind of "batch processing", and exceptions are handled exactly this way -- first one is a cause, others are suppressed. So this practice is somewhat normal.
