### ISSUE TITLE
.exceptionally not getting called if a state that is canceled throws a RuntimeException. 

### ISSUE THREAD

**Issue by lachinois** [vsilaev/tascalate-concurrent#2]
In this example:
 
       State s1 = new State("s1");
       State s2 = new State("s2");

        DependentPromise<String> promise = DependentPromise.from(
                CompletableTask.asyncOn(executorService)
        ).thenApplyAsync(
                (aVoid) -> longTask(...), true
        ).thenApplyAsync(
                (s) -> longTask(...), true
        ).exceptionally(
                (e) -> {
                    System.out.println(e.getMessage());
                    return null;
                }, true
        );

If I call promise.cancel() and lets say that longTask will throw a RuntimeException when it gets interrupted. Should exceptionally() get called since the task did not complete successfully?

**Comment by vsilaev** [comment]
lachinois,

No, it shouldn't be called. You cancel target stage so no transition happens. However, in the following example:

```
State s1 = new State("s1");
   State s2 = new State("s2");

    DependentPromise<String> execPromise = DependentPromise.from(
            CompletableTask.asyncOn(executorService)
    ).thenApplyAsync(
            (aVoid) -> longTask(...), true
    ).thenApplyAsync(
            (s) -> longTask(...), true
    );
    DependentPromise<?> errorPromise = execPromise; 
   .exceptionally(
            (e) -> {
                System.out.println(e.getMessage());
                return null;
            }, true
    );
    execPromise.cancel(true);
```

...block inside `exceptionally` will be called with CompletionException wrapping CancellationException (`execPromise` is not resolved yet, obviously).

**Comment by lachinois** [comment]
Humm... I was puzzled, because in the Javadoc of cancel, it states:

cancel():
if not already completed, completes this CompletableFuture with a CancellationException.

So in theory, the .exceptionally() should complete with a CancellationException and trigger itself at the same time?

**Comment by vsilaev** [comment]
No, this standard behavior -- either you cancel promise and have no trigger, or you cancel a previous promise in chain and have trigger fired. Please compare with standard CompletableFuture:

```
        CompletableFuture<?> f = CompletableFuture.runAsync(() -> {
           try {
               Thread.sleep(1000);
           } catch (final InterruptedException ex) {
               Thread.currentThread().interrupt();
           }
        });
        CompletableFuture<?> z = f.exceptionally(e -> {
            e.printStackTrace(System.out);
            return null;
        }); 
        System.out.println("Z is about to be cancelled...");
        z.cancel(true);
        System.out.println("Z is cancelled");
        if (null != System.out) {
            return;
        }
```
If you cancels `z` as in example above you see no stack trace. If you cancel `f` you have a stack trace.

**Comment by vsilaev** [comment]
Closing the issue while this is expected behavior.
