### ISSUE TITLE
Promises#all(CompletionStage<? extends T>...) cancellation does not seem to work correctly

### ISSUE THREAD

**Issue by skidiver** [vsilaev/tascalate-concurrent#23]
The documentation about `Promises#all(CompletionStage<? extends T>...)` suggests that canceling a `Promise` that has been created using `Promises#all` cancels all `Promisse`s that are wrapped inside. That does not seem to work. Please have a look into 
[CompletableTaskCancellationTest.java.txt](https://github.com/vsilaev/tascalate-concurrent/files/5743402/CompletableTaskCancellationTest.java.txt) methods testWrappedCancel*. (`Executors#getDefaultExecutor()` returns 
`new ThreadPoolTaskExecutor(10, 20, 30, TimeUnit.SECONDS, new LinkedBlockingQueue<>(30))`).

**Comment by vsilaev** [comment]
Hello,
I haven't tested your code, but the issue seems to be related to poorly documented `Promise.dependent()` operator rather than to `Promises.all()` behavior. You should either use `Promise.dependent(PromiseOrigin.ALL)` or add `true` as a last parameter to `thenAccept(...)` - i.e. use overloaded form.
So your code should be either:
```java
    @Test
    public void testWrappedCancelEarly() throws Exception {
        ElapsedTime time = new ElapsedTime();
        Promise<Void> promise0 = CompletableTask.runAsync(taskOf(time, 2000, 0), Executors.getDefaultExecutor());
        Promise<Void> promise1 = CompletableTask.runAsync(taskOf(time, 2000, 1), Executors.getDefaultExecutor());
        Promise<Void> promise2 = CompletableTask.runAsync(taskOf(time, 2000, 2), Executors.getDefaultExecutor());
        Promise<Void> dependentPromise0 = promise0.dependent(PromiseOrigin.ALL).thenAccept(secondStep(time, 1000, 0)); // Use PromiseOrigin.ALL
        Promise<Void> dependentPromise1 = promise1.dependent(PromiseOrigin.ALL).thenAccept(secondStep(time, 1000, 1)); // Use PromiseOrigin.ALL
        Promise<Void> dependentPromise2 = promise2.dependent(PromiseOrigin.ALL).thenAccept(secondStep(time, 1000, 2)); // Use PromiseOrigin.ALL
        Promise<List<Void>> combinedPromise = Promises.all(dependentPromise0, dependentPromise1, ...)
        ...
   }
```
...or...
```java
    @Test
    public void testWrappedCancelEarly() throws Exception {
        ElapsedTime time = new ElapsedTime();
        Promise<Void> promise0 = CompletableTask.runAsync(taskOf(time, 2000, 0), Executors.getDefaultExecutor());
        Promise<Void> promise1 = CompletableTask.runAsync(taskOf(time, 2000, 1), Executors.getDefaultExecutor());
        Promise<Void> promise2 = CompletableTask.runAsync(taskOf(time, 2000, 2), Executors.getDefaultExecutor());
        Promise<Void> dependentPromise0 = promise0.dependent().thenAccept(secondStep(time, 1000, 0), true); // Overloaded operator with true
        Promise<Void> dependentPromise1 = promise1.dependent().thenAccept(secondStep(time, 1000, 1), true); // Overloaded operator with true
        Promise<Void> dependentPromise2 = promise2.dependent().thenAccept(secondStep(time, 1000, 2), true); // Overloaded operator with true
        Promise<List<Void>> combinedPromise = Promises.all(dependentPromise0, dependentPromise1, ...)
        ...
   }
```

**Comment by skidiver** [comment]
Thank you for the quick response. The supposed solutions work fine.

**Comment by skidiver** [comment]
Hi there,
the tests now work very well but unfortunately a real life example does not work. Please have a look onto another test method: 
[reallife.txt](https://github.com/vsilaev/tascalate-concurrent/files/5748229/reallife.txt)
The `sleep(30000);` at the end keeps the programm running. So you can see (on System.out) the threads are still running in background allthough the `combinedPromise` has been canceled after 4s. Maybe interrupting the threads does not work as expected?

**Comment by vsilaev** [comment]
This is expected while your code inside `id -> CompletableTask.runAsync(() -> {})` does not react on interruptions.
Please add the following to `preVisitDirectory` and `visitFile`:
```java
if (Thread.currentThread().isInterrupted()) {
  return FileVisitResult.TERMINATE;
}
```

**Comment by skidiver** [comment]
Thank you, that does the trick. I supposed that `Files#walkFileTree` does those checks. But maybe it is better to add the check outside.
