### ISSUE TITLE
Unconveniences of Promises.failure and Promises.all

### ISSUE THREAD

**Issue by ajurcik** [vsilaev/tascalate-concurrent#3]
Hi Valery,

I would like to have the method `Promises.failure` typed using a type parameter. This would make returning a failed promise easier in cases when the async task was not even started.

The method would look like:

    public static <T> Promise<T> failure(Throwable t) {
        @SuppressWarnings("unchecked")
        CompletablePromise<T> result = (CompletablePromise<T>) new CompletablePromise<Object>();
        result.onFailure(exception);
        return result;
    }

This is inspired by the implementation of `Collections.emptyList()`.

Currently, I am using a workaround. I create a `failure` and I link another stage after it using `thenApply` which allows me to return the desired type.

Regarding `Promises.all` there is a problem with its parameter type. If you would like to specify the aggregated `Promises` differently then by listing them, you need to supply an array of a generic type (a `Promise`). In Java you cannot create such arrays directly. First you need to create a collection and then convert it to the array while you need to do an unchecked cast. It would be more convenient to provide also a method which works with collections.

Anyway, thank you for your great library.
Best, Adam

**Comment by vsilaev** [comment]
Adam,

Thank you for your feedback.
Will definitely take a look.

Meanwhile, could you please provide an example with Promise.failure that shows issues with untyped Promise?

**Comment by ajurcik** [comment]
Hi Valery. Sure.

I have a method which prepares an async computation and during the preparation it can fail, so that the async operation is not started. In such case I wanted to return a failed promise. Please, see the following code:

    public Promise<Result> computeAsync(...) {
        // prepare computation
        if (failed) {
            return Promises.failure(new MyException());
        }
        return startAsyncComputation();
    }

But in the meantime, I realized that it might be better (for me) to have the `computeAsync` method throwing `MyException` when the preparation fails. Then I known that the async operation was not even started and I also have to check for the error (`MyException`).

Finally, it showed that it is probably only false positive use case.

**Comment by vsilaev** [comment]
Adam,

Anyway, I will modify signature as `Promise.failure` and add additional overloads for `all` / `any` as you requested -- it just makes sense and I can't resist :)

A bit out of topic -- could you provide your thoughts on this issue - https://github.com/vsilaev/tascalate-concurrent/issues/4 ?

For next release I planned timeouts functionality, so I'm interesting in your opinion. Btw, afterwards I'm planning to add polling functionality with retry logic.

**Comment by vsilaev** [comment]
Fixed in master, will be in the next release
