### ISSUE TITLE
Promise.onTimeout / completeOnTimeout -- should it cancel original Promise on timeout?

### ISSUE THREAD

**Issue by vsilaev** [vsilaev/tascalate-concurrent#4]
I'd like to open a discussing regarding design choice I made for `Promise.orTimeout ` and `Promise.completeOnTimeout`.

`Promise.orTimeout` returns a new `Promise` that is either completed normally when original `Promise` completes normally within timeout given, or completes exceptionally, when original `Promise` completes exceptionally within timeout given, or completes exceptionally with `TimeoutException` if timeout was exceeded.

When the **returned** `Promise` is cancelled, timeout is cancelled as well. However, **original** `Promise` is not cancelled and its completion code keeps running. Moreover, if timeout happens then **original** `Promise` is not cancelled either.

Why? To support different execution paths depending on timeout duration. For example:
```java
Promise<String> serviceCall = someSlowServiceCall();

serviceCall.orTimeout(Duration.of(5, ChronoUnit.SECONDS)).exceptionally(e -> {
  if (e instanceof TimeoutException) {
    UI.showMessage("Sorry, it takes a bit longer than expected. Please wait...");
  }
});

serviceCall.onTimeout(Duration.of(20, ChronoUnit.SECONDS)).exceptionally(e -> {
  if (e instanceof TimeoutException) {
    if ("Y".equals(UI.showConfirmation("Server does not respond, do you want to cancel operation (Y/N)?"))) {
      serviceCall.cancel();
    }
  }
});
```

Obviously, there is a way to cancel **original** promise as well with minimal coding:
```java
Promise<String> serviceCall = someSlowServiceCall();
Promise<String> withCancelOnTimeout =
  serviceCall
  .orTimeout(Duration.of(5, ChronoUnit.SECONDS), true)
  .exceptionally(e -> serviceCall.cancel(true));
```

`Promise.completeOnTimeout` is almost identical in behavior, the only difference is that in case of timeout the **returned** promise is completed with alternative value (supplied as argument).

Both `orTimeout` and `completeOnTimeout`  are executed on the default executor of the **original** `Promise`.

What do you think?

**Comment by whiskeysierra** [comment]
I faced the same situation/challenge at zalando/riptide. I decided to cancel the original future and propagate the timeout to the returned one, see [here](https://github.com/zalando/riptide/blob/master/riptide-timeout/src/main/java/org/zalando/riptide/timeout/TimeoutPlugin.java#L46):

```java
final ScheduledFuture<?> scheduledTimeout = delay(timeout(downstream), cancel(upstream));
```

I actually like your workaround a lot.

**Comment by vsilaev** [comment]
Willi,

Thank you for suggestion. I'm realizing that cancellation of original promise is more than 95% of case, so I modified an API and added a parameter cancelOnTimeout (by default true in overloaded methods).

Also I renamed completeOnTimeout to onTimeout -- it doesn't complete original promise, so naming should reflect this.

**Comment by ajurcik** [comment]
Hi Valery,

I am sorry that I did not reply. I had a lot of work last week. Anyway, I also thought that functionality will be really wanted so adding a parameters seemed to be a good way also to me. I also thought about the default value and there I thought **keep running** could be default similar to `DependentPromise` and cancellation of its dependents. I would see this as a more conservative approach.

However, when the API provides a parameter, we can always choose. We are not forced to use default values :)

**Comment by vsilaev** [comment]
Adam,

1. The only reason why DependentPromise enlists origins explicitly is the rule of least surprise: when DependentPromise is returned as Promise from some black-box code it should walks and quacks like regular promise and DOES NOT enlist anything silently.
2. In majority of cases there cancelOnTimeout=true is exactly what is necessary. Multiple timeouts over single origin is a boundary case.
3. Promises.all/any/atLeast works the similar way -- cancelRemaining=true if not explicitly specified.

So these are reasons to make cancelOnTimeout=true by default.

By the way, as a requester for DependentPromise you might find it useful to replace DependentPromise.from with Promise.dependent in next release (already in master) -- this way you may just wright chained calls like:
```java
Promise<DataStructure> someMethod(String url) {
  return CompletableTask
             .supplyAsync( () -> loadXml(url) )
             .dependent()
             .thenApplyAsync( xml -> parseXml(xml), true );
}
```

**Comment by ajurcik** [comment]
Ad 1) sounds reasonable.

Ad 2) Sorry, I do not have direct experience with timeouts. It was just the _not cancelling_ behaviour of `FutureTask.get(.. timeout ..)` which I was partially aware of. I just wanted to provide some thoughts for the discussion. More info can be found here: https://stackoverflow.com/questions/16231508/does-a-future-timeout-kill-the-thread-execution.

The new `Promise.dependent` method seems like a useful improvement ragarding the fluency of the API. Thanks.

**Comment by vsilaev** [comment]
>  Sorry, I do not have direct experience with timeouts. It was just the not cancelling behaviour of FutureTask.get(.. timeout ..)

It's implemented differently, via ScheduledExecutorService.schedule + Promise.cancel() -- no time-wait on FutureTask
