### ISSUE TITLE
Exceptions in thenCompose() will not propagate

### ISSUE THREAD

**Issue by chrisly42** [vsilaev/tascalate-concurrent#6]
thenCompose() and derivates are broken when it comes to Exception handling.

This code will never terminate:
```
    @Test
    public void test_exception_handling_with_thenCompose() throws ExecutionException, InterruptedException {
        State s1 = new State();
        Promise<Void> p = CompletableTask.runAsync(() -> longTask(1, s1), executor)
                .thenCompose(it -> {
                    throw new IllegalStateException("oh no!");
                });
        p.get();
    }
```

This code with the CompleteableFuture does:
```
    @Test
    public void test_exception_handling_with_thenCompose2() throws ExecutionException, InterruptedException {
        State s1 = new State();
        Future<Void> p = CompletableFuture.runAsync(() -> longTask(1, s1), executor)
                .thenCompose(it -> {
                    throw new IllegalStateException("oh no!");
                });
        p.get();
    }
```

**Comment by vsilaev** [comment]
Confirmed, fix is committed
Update to the library is planned for this week while it's a pretty severe exception.

Thank you for pointing to it!

**Comment by vsilaev** [comment]
Version [0.6.4](https://github.com/vsilaev/tascalate-concurrent/releases/tag/0.6.4) is released with this bug fix. Should be available shortly on Maven Central. Please verify and close the issue.

Thank you again for your support!

**Comment by chrisly42** [comment]
Works now as expected! Thank you so much for your awesomely quick fix.
