### ISSUE TITLE
whenCompleteAsync adds the failure exception as a suppressed exception to itself

### ISSUE THREAD

**Issue by ajurcik** [vsilaev/tascalate-concurrent#9]
The problem is in the following code:
```
// exceptions are handled in regular way
failure -> {
    try {
        action.accept(null, failure);
        return forwardException(failure);
    } catch (Throwable e) {
        // CompletableFuture does not override exception here
        // unlike as in handle[Async](BiFunction)
        // Preserve this behavior, but let us add at least 
        // suppressed exception
        failure.addSuppressed(e);
        return forwardException(failure);
    }
}
```
The `forwardException` throws a `CompletionException` which is immediatelly caught by the catch clause. Then, it is added to the `failure` as a suppressed exception. However, it can happen that `failure` == `e` (is the same object) since `failure` is retrown when its type already is the `CompletionException`.

I added a test for this in #8.

What about calling the `forwardException` after the `try-catch` block as in the following code? This also make the code a little bit cleaner since there is only one call to `forward...` now :)
 ```
// exceptions are handled in regular way
failure -> {
    try {
        action.accept(null, failure);
    } catch (Throwable e) {
        // CompletableFuture does not override exception here
        // unlike as in handle[Async](BiFunction)
        // Preserve this behavior, but let us add at least 
        // suppressed exception
        failure.addSuppressed(e);
    }
    return forwardException(failure);
}
```

**Comment by ajurcik** [comment]
I already suggested this fix in the same PR (#8).

**Comment by vsilaev** [comment]
Adam,

Will review this tomorrow - but from the first sight it's indeed an issue that must be addressed.
You really have a talent to discover the most non-trivial edge cases! )

Thank you for your PR - most probably I will apply it just "as is"

**Comment by ajurcik** [comment]
Hi Valery, thanks.

I cannot agree with you that I have a talent for this. It is just a user's talent. You know, you provide the users with a functionality and they will immediatelly break it even you tested it :) And I am just an user of your lib here :) Moreover, when I reported this, I realized that I used your library in a wrong way!

I am not dependent on the issue, so take your time.

**Comment by vsilaev** [comment]
Adam,
Your fix was verified and merged, thank you!

Btw, did you have a chance to try out Promises.retry / poll / pollOptional functionality?
Frankly, I didn't spent a good amount of time for deep testing here...

**Comment by ajurcik** [comment]
Sorry, I had no need to use the retry/poll functionality yet. Thanks for fixing!
